folder_in: /Users/Pavel_Shev/Desktop/tst
folder_out: /Users/Pavel_Shev/Desktop/out
folder_ext: /Users/Pavel_Shev/Desktop/folder1
folder_ext2: /Users/Pavel_Shev/Desktop/folder2
count: 5
bs: 1M
type: zip
ip: 0.0.0.0
user: user
passwd: 1111
local_path: /Users/Pavel_Shev/Desktop/p7zip-full.deb
remote_path: /Users/Pavel_Shev/Desktop/p7zip-full.deb
archive_type: zip
